// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TESTT.Models;

#nullable disable

namespace TESTT.Migrations
{
    [DbContext(typeof(CatchTIMEContext))]
    [Migration("20240119153041_UpdateTaskId")]
    partial class UpdateTaskId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TESTT.Models.List", b =>
                {
                    b.Property<int>("ListId")
                        .HasColumnType("int")
                        .HasColumnName("list_id");

                    b.Property<string>("ListCategory")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("list_category");

                    b.Property<string>("ListName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("list_name");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ListId");

                    b.HasIndex("UserId");

                    b.ToTable("List", (string)null);
                });

            modelBuilder.Entity("TESTT.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<int?>("ListId")
                        .HasColumnType("int")
                        .HasColumnName("list_id");

                    b.Property<int?>("ProjectNoOfCompleted")
                        .HasColumnType("int")
                        .HasColumnName("project_no_of_completed");

                    b.Property<int?>("ProjectNoOfTasks")
                        .HasColumnType("int")
                        .HasColumnName("project_no_of_tasks");

                    b.Property<string>("ProjectTitle")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("project_title");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ProjectId");

                    b.HasIndex("ListId");

                    b.HasIndex("UserId");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("TESTT.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("TaskId");

                    b.Property<int?>("ListId")
                        .HasColumnType("int")
                        .HasColumnName("ListId");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectId");

                    b.Property<TimeSpan?>("TaskActualDuration")
                        .HasColumnType("time")
                        .HasColumnName("TaskActualDuration");

                    b.Property<DateTime?>("TaskDate")
                        .HasColumnType("date")
                        .HasColumnName("TaskDate");

                    b.Property<int?>("TaskDifficulty")
                        .HasColumnType("int")
                        .HasColumnName("TaskDifficulty");

                    b.Property<TimeSpan?>("TaskDuration")
                        .HasColumnType("time")
                        .HasColumnName("TaskDuration");

                    b.Property<TimeSpan?>("TaskEndTime")
                        .HasColumnType("time")
                        .HasColumnName("TaskEndTime");

                    b.Property<int?>("TaskPriority")
                        .HasColumnType("int")
                        .HasColumnName("TaskPriority");

                    b.Property<TimeSpan?>("TaskStartTime")
                        .HasColumnType("time")
                        .HasColumnName("TaskStartTime");

                    b.Property<string>("TaskStatus")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TaskStatus");

                    b.Property<string>("TaskTag")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TaskTag");

                    b.Property<string>("TaskTitle")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TaskTitle");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("TaskId");

                    b.HasIndex("ListId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TESTT.Models.UserTable", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserActivities")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_activities");

                    b.Property<int?>("UserAge")
                        .HasColumnType("int")
                        .HasColumnName("user_age");

                    b.Property<DateTime?>("UserBirthdate")
                        .HasColumnType("date")
                        .HasColumnName("user_birthdate");

                    b.Property<string>("UserCountry")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_country");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserFirstname")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_firstname");

                    b.Property<string>("UserLastname")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_lastname");

                    b.Property<string>("UserPassword")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_password");

                    b.Property<TimeSpan?>("UserProductivityTime")
                        .HasColumnType("time")
                        .HasColumnName("user_productivity_time");

                    b.Property<TimeSpan?>("UserSleeptime")
                        .HasColumnType("time")
                        .HasColumnName("user_sleeptime");

                    b.Property<string>("UserStatus")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_status");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__User_Tab__B9BE370F555B4770");

                    b.ToTable("User_Table", (string)null);
                });

            modelBuilder.Entity("TESTT.Models.List", b =>
                {
                    b.HasOne("TESTT.Models.UserTable", "User")
                        .WithMany("Lists")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__List__user_id__398D8EEE");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TESTT.Models.Project", b =>
                {
                    b.HasOne("TESTT.Models.List", "List")
                        .WithMany("Projects")
                        .HasForeignKey("ListId")
                        .HasConstraintName("FK__Project__list_id__3D5E1FD2");

                    b.HasOne("TESTT.Models.UserTable", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Project__user_id__3C69FB99");

                    b.Navigation("List");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TESTT.Models.Task", b =>
                {
                    b.HasOne("TESTT.Models.List", "List")
                        .WithMany("Tasks")
                        .HasForeignKey("ListId")
                        .HasConstraintName("FK__Tasks__list_id__412EB0B6");

                    b.HasOne("TESTT.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__Tasks__project_i__4222D4EF");

                    b.HasOne("TESTT.Models.UserTable", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Tasks__user_id__403A8C7D");

                    b.Navigation("List");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TESTT.Models.List", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TESTT.Models.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TESTT.Models.UserTable", b =>
                {
                    b.Navigation("Lists");

                    b.Navigation("Projects");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
